import = ["/home/slani/.config/alacritty/everforest_dark.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 12.0

[window]
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.97
