unsetopt beep
bindkey -v
zstyle :compinstall filename '/home/slani/.zshrc'

# Completion
autoload -Uz compinit
compinit
_comp_options+=(globdots) # With hidden files

# User config dir
if [ -d ~/.zshrc.d ]; then
        for rc in ~/.zshrc.d/*; do
        	if [ -f "$rc" ]; then
                	. "$rc"
        	fi
	done
fi
